### PR TITLE
Make Final a repr(transparent) and no-std newtype

### PR DESCRIPTION
**Pull request by juntyr**
- Adds the `#[repr(transparent)]` attribute to `Final` for better ABI compatibility
- Makes the library `no-std` compatible

### CODE REVIEW

**Comment by juntyr** [comment]
@jswrenn (When) Could you have a look at this PR? Thanks in advance :)

**Comment by jswrenn** [comment]
Sorry for the delay, and thanks for the reminder! August was a tough month for me, and I totally missed this PR.

**Comment by juntyr** [comment]
Thanks for the quick reply (and no worries)! Could you also create a new crates.io release with the change? Thank you for your help!

**Comment by jswrenn** [comment]
Done!

**Comment by juntyr** [comment]
> Done!

@jswrenn Awesome, thank you so much!

**Pull request merged**
